import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { GoogleGenAI } from "@google/genai";
import { db } from "@/db";
import { sessions, reports, users } from "@/db/schema";
import { eq } from "drizzle-orm";
import React from "react";

// Vercel: allow up to 60s for Gemini + PDF + Cloudinary
export const maxDuration = 60;
export const runtime = "nodejs";

// ── PDF styles ────────────────────────────────────────────────────────────────
const S = StyleSheet.create({
  page:      { padding: 48, backgroundColor: "#FFFBF7", fontFamily: "Helvetica" },
  brand:     { fontSize: 22, fontWeight: "bold", color: "#D85A30" },
  brandSub:  { fontSize: 11, color: "#993C1D", marginTop: 2 },
  divider:   { height: 1, backgroundColor: "#F2E4DB", marginVertical: 14 },
  metaRow:   { flexDirection: "row", marginBottom: 4 },
  metaLabel: { fontSize: 10, fontWeight: "bold", color: "#993C1D", width: 80 },
  metaVal:   { fontSize: 10, color: "#4A1B0C" },
  secTitle:  { fontSize: 13, fontWeight: "bold", color: "#4A1B0C", marginBottom: 8 },
  summary:   { fontSize: 11, color: "#4A1B0C", lineHeight: 1.6 },
  bubble:    { marginBottom: 8, padding: 8, borderRadius: 6 },
  userBubble:{ backgroundColor: "#EEEDFE" },
  aiBubble:  { backgroundColor: "#FFF3EC" },
  bubbleLabel:{ fontSize: 8, fontWeight: "bold", marginBottom: 3 },
  userLabel: { color: "#7F77DD" },
  aiLabel:   { color: "#D85A30" },
  bubbleText:{ fontSize: 10, color: "#26215C", lineHeight: 1.5 },
  footer:    { position: "absolute", bottom: 32, left: 48, right: 48, fontSize: 9, color: "#C4A99A", textAlign: "center" },
});

type Entry = { role: "user" | "ai"; text: string };

function SessionPDF({ subject, date, duration, summary, transcript }: {
  subject: string; date: string; duration: string; summary: string; transcript: Entry[];
}) {
  return (
    <Document title={`TutorTalk — ${subject} Session`} author="TutorTalk">
      <Page size="A4" style={S.page}>
        {/* Brand header */}
        <Text style={S.brand}>TutorTalk</Text>
        <Text style={S.brandSub}>AI-Powered Socratic Tutor</Text>
        <View style={S.divider} />

        {/* Session meta */}
        <View style={S.metaRow}><Text style={S.metaLabel}>Subject</Text><Text style={S.metaVal}>{subject}</Text></View>
        <View style={S.metaRow}><Text style={S.metaLabel}>Date</Text><Text style={S.metaVal}>{date}</Text></View>
        <View style={S.metaRow}><Text style={S.metaLabel}>Duration</Text><Text style={S.metaVal}>{duration}</Text></View>
        <View style={S.divider} />

        {/* AI summary */}
        <Text style={S.secTitle}>Session Summary</Text>
        <Text style={S.summary}>{summary}</Text>
        <View style={S.divider} />

        {/* Transcript */}
        <Text style={S.secTitle}>Conversation Transcript</Text>
        {transcript.map((e, i) => (
          <View key={i} style={[S.bubble, e.role === "user" ? S.userBubble : S.aiBubble]}>
            <Text style={[S.bubbleLabel, e.role === "user" ? S.userLabel : S.aiLabel]}>
              {e.role === "user" ? "You" : "TutorTalk"}
            </Text>
            <Text style={S.bubbleText}>{e.text}</Text>
          </View>
        ))}

        <Text style={S.footer}>Generated by TutorTalk · tutortalk.vercel.app</Text>
      </Page>
    </Document>
  );
}

// ── Route handler ─────────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { sessionId } = await req.json();
  if (!sessionId) return NextResponse.json({ error: "sessionId required" }, { status: 400 });

  // Verify session belongs to this user
  const user = await db.select().from(users).where(eq(users.clerkId, userId)).limit(1);
  if (!user.length) return NextResponse.json({ error: "User not found" }, { status: 404 });

  const session = await db.select().from(sessions).where(eq(sessions.id, sessionId)).limit(1);
  if (!session.length) return NextResponse.json({ error: "Session not found" }, { status: 404 });
  if (session[0].userId !== user[0].id) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { subject, transcript: rawTranscript, durationSecs, startedAt } = session[0];
  const transcript: Entry[] = rawTranscript ? JSON.parse(rawTranscript) : [];

  // ── 1. Generate summary with Gemini 3.1 Flash ────────────────────────────
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

  const transcriptText = transcript
    .map(e => `${e.role === "user" ? "Student" : "TutorTalk"}: ${e.text}`)
    .join("\n");

  const prompt =
    `You are writing a session report for a student who just completed a ${subject} tutoring session with TutorTalk (an AI Socratic tutor).\n\n` +
    `Transcript:\n${transcriptText || "(No transcript recorded)"}\n\n` +
    `Write a concise, encouraging session report in plain text with these 4 sections:\n` +
    `1. Topics Covered — what concepts were discussed (2-3 bullet points)\n` +
    `2. Student Strengths — what they understood well (2-3 bullet points)\n` +
    `3. Areas to Improve — what needs more practice (2-3 bullet points)\n` +
    `4. Next Steps — specific topics to study next (2-3 bullet points)\n\n` +
    `Keep it warm, specific, and motivating. Use plain text bullets with "•" character.`;

  let summary = "";
  try {
    const result = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: prompt,
    });
    summary = result.text ?? "";
  } catch {
    summary = "Summary generation failed — see transcript below for full session details.";
  }

  // ── 2. Render PDF ────────────────────────────────────────────────────────
  const date = new Date(startedAt ?? Date.now()).toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric",
  });
  const mins = Math.floor((durationSecs ?? 0) / 60);
  const secs = (durationSecs ?? 0) % 60;
  const duration = `${mins}m ${secs}s`;

  const pdfBuffer = await renderToBuffer(
    React.createElement(SessionPDF, { subject: subject ?? "", date, duration, summary, transcript })
  );

  // ── 3. Store PDF in DB (base64) ──────────────────────────────────────────
  const pdfData = Buffer.from(pdfBuffer).toString("base64");
  const pdfUrl = `/api/session/pdf?sessionId=${sessionId}`;

  // ── 4. Save to reports table ─────────────────────────────────────────────
  await db.insert(reports).values({ sessionId, pdfUrl, pdfData, summary });

  return NextResponse.json({ pdfUrl });
}
